# Generated by Django 4.2.4 on 2023-08-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creat_at',
            new_name='created_at',
        ),
    ]
